server:
  port: 9797

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wds?useUnicode=true&allowMultiQueries=true
    username: root
    password: sinocom11

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

ignore:
  path: /user/login